---
- name: Generate Markdown report
  ansible.builtin.command:
    cmd: "{{ automan_python }} -m automan_core report -i {{ automan_config_file }}"
  args:
    chdir: "{{ automan_root }}"
  register: report_result
  changed_when: true
  tags:
    - report

- name: Show report path
  ansible.builtin.debug:
    msg: "{{ report_result.stdout }}"
  tags:
    - report
