database_profile:
  id: ymatrix_heap_master_only
  display_name: YMatrix heap master only
  database_type: ymatrix
  storage_engine: heap
  test_mode: master_only

  tpcc:
    ddl_profile: ymatrix_heap_master_only
    ddl_dir: benchmarks/tpcc/benchmarksql/ddl/ymatrix_heap_master_only
    benchmarksql_db: postgres
    table_strategy: heap_master_only
    requires_ddl_confirmation: false
