CREATE TABLE tpch.part
(P_PARTKEY INT,
P_NAME TEXT :MARS_ENCODING,
P_MFGR TEXT,
P_BRAND TEXT :MARS_ENCODING,
P_TYPE TEXT :MARS_ENCODING,
P_SIZE SMALLINT :MARS_ENCODING,
P_CONTAINER TEXT :MARS_ENCODING,
P_RETAILPRICE float8,
P_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS_BTREE_INDEX;
